### ISSUE TITLE
Docker swarm mode compatibility

### ISSUE THREAD

**Issue by Danny4927** [brunocfnba/docker-spark-cluster#2]
Hey, nice images. This solution is only working on a single machine? I am trying to use this with docker swarm. Is it possible to make it Docker swarm mode compatibile?

**Comment by brunocfnba** [comment]
Hey Danny,

I believe they are not swarm ready at the moment but I'm working on a Kubernetes implementation using deployments. Should be live soon.

**Comment by Danny4927** [comment]
Hey @brunocfnba, i already made a swarm ready version. Here is the yaml file with explanation: https://github.com/Danny4927/docker-spark

**Comment by weyndahir** [comment]
Great work guys! quick question 
 what steps do I need to take in order to create one container for all these four containers and deployed into Mesos Cluster, so that my job will be scheduled and run everyday as expected. thanks in advance! JJ

**Comment by weyndahir** [comment]
the second question will be for brunocfnba in you scrip file there is a folder call data/crontab I am not seeing when this file was created in the process.

**Comment by brunocfnba** [comment]
Hey guys, I've published a Spark Kubernetes version. Please share your thoughts.
